/**
 * The browser half of the tmux-web WebSocket protocol: one socket carrying PTY
 * bytes and JSON control messages behind a one-byte frame-type prefix.
 *
 * The Go half is `internal/ptybridge/frame.go` (the prefix codec) and
 * `internal/front/ws.go` (the control messages). Both sides implement this
 * independently, so the constants and field names here are a cross-language
 * contract; `transport.test.ts` pins them against the Go source for that
 * reason, the same way `TestFrameWireBytes` pins them on the Go side.
 *
 * ## Why this exists instead of `@wterm/core`'s `WebSocketTransport`
 *
 * That class buffers `send()` while the socket is not OPEN and flushes the
 * buffer on the next open (`_flushBuffer`). For a plain shell that is a
 * convenience; here it is a hazard. A reconnect in this app creates a *new*
 * throwaway tmux session, which lands on whatever window and pane the group's
 * active window happens to be. Keystrokes typed into a dead socket would then
 * be replayed into a different agent's shell some seconds later. There is no
 * safe place to put those bytes, so they are dropped at the point of the write
 * and `send` says so by returning false.
 *
 * The invariant is structural rather than defensive: a Transport owns exactly
 * one WebSocket for its whole life, holds no outbound queue at all, and never
 * reopens. Reconnecting means constructing a new Transport -- which is also
 * where the caller (the terminal component) restores the remembered
 * `session:window.pane` before it re-enables input.
 *
 * ## Keepalive
 *
 * The server pings every ~20s. Nothing is needed here: RFC 6455 pongs are
 * generated by the browser's network stack below the JavaScript API, which
 * exposes neither ping nor pong. That is also why a backgrounded tab keeps
 * answering while its timers are throttled -- worth knowing, since a tab that
 * stopped ponging would have its tmux client torn down.
 */

/** Frame kinds. Mirrors `ptybridge.FrameData` / `ptybridge.FrameControl`. */
export const FRAME_DATA = 0x00
export const FRAME_CONTROL = 0x01

/**
 * Largest data payload put in one frame.
 *
 * `wsReadLimit` in `internal/front/ws.go` bounds an inbound message at 1MiB and
 * coder/websocket kills the connection when a message exceeds it, so an
 * unchunked paste of a large file would take the terminal down with it. Half a
 * megabyte leaves generous room for the prefix byte and for the limit moving.
 * Splitting is safe in this direction for the same reason it is in the other:
 * the far end is a PTY, which consumes a byte stream and neither knows nor
 * cares where the frame boundaries fell.
 */
export const MAX_DATA_PAYLOAD = 1 << 19

/**
 * WebSocket.OPEN. Spelled out rather than read off the global so that the
 * constant does not depend on which WebSocket implementation is in scope.
 */
const WS_OPEN = 1

/**
 * A control message the server understands.
 *
 * The `type` strings and field names must match `wsControlMessage` and the
 * switch in `control()` in `internal/front/ws.go`. `pane` is a tmux pane id
 * (`%3`); the server refuses anything else, since `tmux select-pane -t work`
 * exits 0 and moves the pane the *user* is sitting in front of.
 */
export type ControlMessage =
  | { type: 'resize'; cols: number; rows: number }
  | { type: 'select'; pane: string }
  | { type: 'copy-mode'; pane?: string }

/** Why the socket ended, as far as the caller needs to decide what to do next. */
export interface TransportClose {
  /** WebSocket close code. 1000 with reason "session ended" is tmux exiting. */
  code: number
  reason: string
  wasClean: boolean
}

export interface TransportOptions {
  /** Absolute or relative ws:// URL, including the `?session=` parameter. */
  url: string

  /**
   * Sink for `0x00` frames: raw PTY bytes, to be handed to the terminal.
   *
   * The array is a view onto the message's own buffer, which is fresh per
   * message and not reused, so it may be retained. It is never the whole
   * frame -- the prefix byte is already off.
   */
  onData: (bytes: Uint8Array) => void

  /**
   * Sink for `0x01` frames, parsed as JSON. The server sends none today; this
   * exists so that when it does, the byte stream is not where they land.
   */
  onControl?: (message: unknown) => void

  onOpen?: () => void

  /**
   * The socket ended. This is the caller's cue to reconnect, and the reason it
   * gets a code: a clean 1000 means the tmux session itself ended and there is
   * nothing to reconnect to, while anything else is a fault worth retrying.
   *
   * Not called for a close the caller asked for via `close()`.
   */
  onClose?: (event: TransportClose) => void

  onError?: (event: Event) => void
}

/** Where a Transport is in its one and only life. */
export type TransportState = 'connecting' | 'open' | 'closed'

const encoder = new TextEncoder()
const decoder = new TextDecoder()

/**
 * One WebSocket to one tmux attach. Connects on construction; once closed it
 * stays closed.
 *
 * The constructor throws whatever `new WebSocket(url)` throws -- a syntactically
 * bad url, or a ws:// url on an https:// page. Both are programming errors
 * rather than network conditions, so they are left to surface rather than being
 * turned into a close event the caller would retry forever.
 */
export class Transport {
  readonly url: string

  readonly #ws: WebSocket
  readonly #opts: TransportOptions

  /**
   * Set by `close()`. Suppresses every callback from that point on, so a
   * caller that tore this Transport down does not then get an `onClose` it
   * would read as a network drop and reconnect from.
   */
  #closedByCaller = false

  constructor(opts: TransportOptions) {
    this.#opts = opts
    this.url = opts.url

    const ws = new WebSocket(opts.url)

    // Binary frames arrive as Blobs by default, which are only readable
    // asynchronously. Two Blob reads on a byte stream can settle out of order,
    // and a terminal stream reordered is a terminal corrupted -- an escape
    // sequence delivered after the text it was meant to style. "arraybuffer"
    // is synchronous, so ordering is the socket's ordering, and it saves an
    // allocation and a microtask per frame on the hottest path there is.
    ws.binaryType = 'arraybuffer'

    ws.onopen = () => {
      if (!this.#closedByCaller) this.#opts.onOpen?.()
    }
    ws.onmessage = (event: MessageEvent) => this.#receive(event)
    ws.onclose = (event: CloseEvent) => {
      if (this.#closedByCaller) return
      this.#opts.onClose?.({
        code: event.code,
        reason: event.reason,
        wasClean: event.wasClean,
      })
    }
    ws.onerror = (event: Event) => {
      if (!this.#closedByCaller) this.#opts.onError?.(event)
    }

    this.#ws = ws
  }

  get state(): TransportState {
    if (this.#closedByCaller) return 'closed'
    switch (this.#ws.readyState) {
      case 0:
        return 'connecting'
      case WS_OPEN:
        return 'open'
      default:
        // CLOSING counts as closed: nothing written from here on will arrive.
        return 'closed'
    }
  }

  get connected(): boolean {
    return this.state === 'open'
  }

  /**
   * Send PTY input. Strings are encoded as UTF-8, which is what
   * `@wterm/react`'s `onData` hands over and what the PTY expects.
   *
   * Returns false when the socket is not open, in which case the bytes are
   * *gone*: see the note at the top of this file. Nothing is queued, here or
   * anywhere below.
   *
   * There is deliberately no `bufferedAmount` check. The only thing that fills
   * that buffer is a server that has stopped reading, which the Go side does
   * not do -- it drops the connection instead of blocking, so backpressure
   * arrives as a close, not as a stall. Dropping keystrokes to defend a buffer
   * that a terminal's uplink (keystrokes and the occasional paste) cannot fill
   * would trade a theoretical problem for silently losing what the user typed.
   */
  send(data: string | Uint8Array): boolean {
    const bytes = typeof data === 'string' ? encoder.encode(data) : data
    if (bytes.length <= MAX_DATA_PAYLOAD) return this.#write(FRAME_DATA, bytes)
    for (let i = 0; i < bytes.length; i += MAX_DATA_PAYLOAD) {
      if (!this.#write(FRAME_DATA, bytes.subarray(i, i + MAX_DATA_PAYLOAD))) {
        return false
      }
    }
    return true
  }

  /** Send a control message. Returns false if the socket is not open. */
  sendControl(message: ControlMessage): boolean {
    return this.#write(FRAME_CONTROL, encoder.encode(JSON.stringify(message)))
  }

  /** Tell the server the terminal's new size. Debouncing is the caller's job. */
  resize(cols: number, rows: number): boolean {
    return this.sendControl({ type: 'resize', cols, rows })
  }

  /**
   * Move this tab's own session to a pane, by tmux pane id (`%3`). Other tabs
   * and the user's local attach are unaffected.
   */
  select(pane: string): boolean {
    return this.sendControl({ type: 'select', pane })
  }

  /** Put a pane into tmux copy-mode; omit the pane for this tab's current one. */
  copyMode(pane?: string): boolean {
    return this.sendControl(pane === undefined ? { type: 'copy-mode' } : { type: 'copy-mode', pane })
  }

  /**
   * Close the socket. Idempotent, and final: this Transport cannot be
   * reopened, and no further callback fires.
   */
  close(code = 1000, reason = ''): void {
    if (this.#closedByCaller) return
    this.#closedByCaller = true
    this.#ws.close(code, reason)
  }

  #write(kind: number, payload: Uint8Array): boolean {
    if (!this.connected) return false
    const frame = new Uint8Array(payload.length + 1)
    frame[0] = kind
    frame.set(payload, 1)
    this.#ws.send(frame)
    return true
  }

  #receive(event: MessageEvent): void {
    if (this.#closedByCaller) return

    // The server sends binary only, and `binaryType` above asks for buffers.
    // Anything else means the two ends disagree about the protocol; it is
    // dropped rather than closing the socket, because a terminal is expensive
    // to lose and a frame is not.
    if (!(event.data instanceof ArrayBuffer)) {
      console.warn('transport: ignoring non-binary message', typeof event.data)
      return
    }
    const frame = new Uint8Array(event.data)
    if (frame.length === 0) {
      console.warn('transport: ignoring empty frame')
      return
    }

    // A frame carrying only a prefix is valid and yields an empty payload,
    // matching ptybridge.Decode.
    const payload = frame.subarray(1)
    switch (frame[0]) {
      case FRAME_DATA:
        this.#opts.onData(payload)
        return
      case FRAME_CONTROL:
        this.#control(payload)
        return
      default:
        console.warn('transport: ignoring frame with unknown kind', frame[0])
    }
  }

  #control(payload: Uint8Array): void {
    let message: unknown
    try {
      message = JSON.parse(decoder.decode(payload))
    } catch {
      console.warn('transport: ignoring malformed control message')
      return
    }
    this.#opts.onControl?.(message)
  }
}
