package report

import (
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/diegok/tmux-web/internal/integrations"
)

// The three integrations' event lists, held against this table. All three
// unconditionally.
//
// WHAT THIS FILE IS FOR. Every agent's integration carries a list of the events
// it subscribes to, in its own language, and this package carries what each of
// those events MEANS. The two lists are the same list written twice, and until
// this package existed only claude's pair was held together by anything that
// always runs:
//
//   - claude's hooks are generated by internal/integrations, which cannot
//     import package main, so the tie lived in cmd/tmux-web. It moves here
//     unchanged, because this is now the package that can see both.
//   - opencode's `busEvents` was tied to the table only by the live-bus wiring
//     test, which SKIPS on a machine with no opencode installed -- which is
//     every CI machine and most developer machines.
//   - pi's handler list was written out in pi.test.ts and tied to nothing over
//     here at all. vitest holds the extension's registration to that literal;
//     nothing held the literal to this table.
//
// So the two new tests read the integration SOURCE -- the same bytes the
// installer writes to disk, out of the same embed.FS -- and hold the names in
// it to the table. Reading source is a blunt instrument and it is chosen
// deliberately over the alternatives: a real runtime is what SKIPS, and a
// generated list would mean generating JavaScript from Go, which is a build
// step and a whole new way for the two to disagree. The bluntness is bounded by
// the assertions each test makes about its own parse: a regex that stops
// matching yields an empty set, and an empty set fails.
//
// What they do NOT check is that the integration is WIRED to what it says --
// that the plugin's `event` hook really is called for the names in busEvents,
// that pi's default export really registers its handlers. That needs a runtime,
// and it is what the skippable wiring tests and the vitest suites are for. The
// division is: the runtime tests prove the integration works, and these prove
// it is talking about the events this table maps.

// reportedEvent matches the event NAME an integration passes to
// `tmux-web report --event`.
//
// Both files spell the call the same way -- report({ event: '<name>' ... }) --
// because both queue an item shaped {event, payload}. It is the name on the
// command line that has to be a name this table maps, so it is the name this
// reads, rather than the handler key it happens to sit under.
var reportedEvent = regexp.MustCompile(`report\(\{ event: '([^']+)'`)

// busEventsSet matches opencode's forwarding whitelist.
//
// opencode is the one integration whose events do not all arrive as hooks of
// their own: four of the six come off the plugin bus, through a single `event`
// hook, and are forwarded by name. That name is `event.type` at the call site,
// so reportedEvent cannot see it and this set is where it is written down.
var busEventsSet = regexp.MustCompile(`const busEvents = new Set\(\[([^\]]*)\]\)`)

// quoted pulls the single-quoted strings out of one JavaScript expression.
var quoted = regexp.MustCompile(`'([^']+)'`)

// TestTheRegisteredClaudeHooksAreExactlyTheEventsTheTableKnows binds the
// installer's hook set to this table, in both directions.
//
// Both directions, because each is a different defect:
//
//   - A registered hook with no mapping fires into nothing. It is the quietest
//     failure in this feature: the settings block is still four hooks, every
//     one still `"async": true`, still no asyncRewake and still no
//     SubagentStop -- every assertion in claude_hooks_test.go passes. The hook
//     still fires, the wrapper still runs, `report` still exits 0. It just
//     prints `nothing known about "claude"'s "PreToolCall" event` to a stderr
//     nobody reads and writes no state at all.
//   - A mapped event nobody registers is a row that can never run. Harmless in
//     itself, and a reliable sign that somebody added an event to the table and
//     forgot that Claude has no runtime to discover it -- unlike pi and
//     opencode, where the integration subscribes by name, Claude only ever
//     sends what settings.json asked for.
//
// The pi and opencode equivalents cannot happen as quietly, because their
// wiring tests drive a REAL runtime and watch what it spawns; Claude has no
// such test, because driving a real Claude Code needs the owner's credentials
// and spends the owner's quota.
func TestTheRegisteredClaudeHooksAreExactlyTheEventsTheTableKnows(t *testing.T) {
	assertSameEvents(t, "claude", "the installer's settings.json block",
		integrations.ClaudeHookEvents)
}

// TestTheOpencodePluginForwardsExactlyTheEventsTheTableKnows holds
// opencode.js's own lists to this table.
//
// The plugin's six names arrive two ways -- two are hooks of their own,
// `chat.message` and `tool.execute.before`, and four come off the bus through
// the `event` hook and its busEvents whitelist -- and the union is what this
// checks. Both halves matter and they fail differently:
//
//   - A NAME IN THE PLUGIN THE TABLE DOES NOT MAP is a process per event for
//     nothing. opencode's bus is chatty -- one message.part.updated per
//     streamed chunk, 45 plugin.added at startup -- so the whitelist is the
//     difference between six forks a turn and dozens, and a name added to it
//     that the table ignores buys the forks and no badge.
//   - A NAME IN THE TABLE THE PLUGIN DOES NOT FORWARD is a row that can never
//     run. Not harmless here: the turn end is `session.idle`, and a busEvents
//     that lost it is a pane that never clears.
//
// It reads the embedded source rather than a live opencode because the live
// test skips wherever opencode is not installed, which is where this drift
// would be introduced.
func TestTheOpencodePluginForwardsExactlyTheEventsTheTableKnows(t *testing.T) {
	src := integrationSource(t, "opencode.js")

	// The two hooks that are named at their call site.
	named := matchAll(reportedEvent, src)
	if len(named) != 2 {
		t.Fatalf("found %v reported by name in opencode.js, want the two hooks of its own "+
			"(chat.message and tool.execute.before). A parse that stopped matching would make "+
			"this test pass by finding nothing on both sides", named)
	}

	// The four the bus forwards, whose name at the call site is event.type.
	set := busEventsSet.FindStringSubmatch(src)
	if set == nil {
		t.Fatal("opencode.js no longer declares `const busEvents = new Set([...])`: this test " +
			"cannot see the forwarding whitelist, and an unread whitelist is an unheld one")
	}
	bus := matchAll(quoted, set[1])
	if len(bus) == 0 {
		t.Fatal("busEvents is empty: the plugin forwards nothing off the bus")
	}

	assertSameEvents(t, "opencode", "opencode.js's hooks and busEvents", append(named, bus...))
}

// TestThePiExtensionReportsExactlyTheEventsTheTableKnows holds pi.ts's handlers
// to this table.
//
// pi.test.ts already asserts that the default export registers exactly five
// names, written out as a literal -- and that literal was tied to nothing on
// this side. This is the other end of it: the names the extension puts on the
// command line are names this table maps, and every row of the pi table is a
// row some handler can reach.
//
// It reads the reported names rather than the handler keys because the reported
// name is what becomes `--event`. The two are the same string today, and
// vitest's registration test is what holds the handler keys; a handler that
// reported under a different name than it registered under would fail here.
func TestThePiExtensionReportsExactlyTheEventsTheTableKnows(t *testing.T) {
	reported := matchAll(reportedEvent, integrationSource(t, "pi.ts"))
	if len(reported) == 0 {
		t.Fatal("no `report({ event: '...' })` call found in pi.ts: this test cannot see the " +
			"handler list, and an unread list is an unheld one")
	}
	assertSameEvents(t, "pi", "pi.ts's handlers", reported)
}

// assertSameEvents is the comparison all three ties make: the integration's
// list and this table's row set, in both directions, as sorted text so the
// failure names the difference.
func assertSameEvents(t *testing.T, agent, what string, sent []string) {
	t.Helper()
	mapped := make([]string, 0, len(rules[agent].events))
	for event := range rules[agent].events {
		mapped = append(mapped, event)
	}
	if len(mapped) == 0 {
		t.Fatalf("this table maps no events for %s at all; the comparison below would prove nothing", agent)
	}
	sent = dedupe(sent)
	sort.Strings(sent)
	sort.Strings(mapped)
	if strings.Join(sent, " ") != strings.Join(mapped, " ") {
		t.Errorf("%s sends %v; internal/report maps %v.\n"+
			"An event the integration sends and this table does not map writes no state and prints "+
			"one line to a stderr nobody reads. An event this table maps and the integration never "+
			"sends is a row that can never run.", what, sent, mapped)
	}
}

// integrationSource is the integration file as the installer writes it: the
// embedded copy, not a path on disk, so this test reads the same bytes that
// reach the user's machine.
func integrationSource(t *testing.T, name string) string {
	t.Helper()
	b, err := integrations.File(name)
	if err != nil {
		t.Fatalf("reading the embedded %s: %v", name, err)
	}
	return string(b)
}

// matchAll is every first submatch of re in s.
func matchAll(re *regexp.Regexp, s string) []string {
	var out []string
	for _, m := range re.FindAllStringSubmatch(s, -1) {
		out = append(out, m[1])
	}
	return out
}

// dedupe keeps the comparison a set comparison. An integration may report the
// same event from two places -- nothing does today -- and that is not a drift.
func dedupe(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}
